### ISSUE TITLE
Is there any test about the limit of graph size?

### ISSUE THREAD

**Issue by LspongebobJH** [dmlc/GNNLens2#11]
Hi there,

I'm wondering if the limit of graph size has been tested, such as the maximal number of nodes and edges in the visualized graph? And the correspondence between the memory overhead/simulation time and the graph size also interests me. For example, how big the graph is that can be processed by the GNNLens2 within 10secs on a machine with 16 CPUs and 64GB memory?

**Comment by mufeili** [comment]
I did not test that.
