### ISSUE TITLE
Support for heterogeneous graphs

### ISSUE THREAD

**Issue by Mrugankakarte** [dmlc/GNNLens2#12]
Thanks for this wonderful library. In writer.add_graph(), I saw that it only accepts homogeneous graphs, do you have any plans to support heterogeneous graphs?

**Comment by mufeili** [comment]
@Mrugankakarte Thank you for the suggestion. We are aware that supporting heterogeneous graphs can be a promising direction. However, at this point I cannot guarantee if this will be realized and if so when. For the time being, you can encode node types with node classes (colors).

**Comment by Mrugankakarte** [comment]
Thanks. Closing this for now.
